### ISSUE TITLE
Isn't this project no longer maintained ?

### ISSUE THREAD

**Issue by vipwan** [simplcommerce/SimplCommerce#1053]
Such a good open source project, what a pity

**Comment by hishamco** [comment]
@thiennn as I saw many feedback a while ago is this project still maintained by you or did you stop working on it, if you no longer maintain it or you are busy, can you transfer the ownership to me or let us find a way to make this project active. frankly, I stopped pushing any PR since I feel the project is inactive

**Comment by MertDenizKaratas** [comment]
Is there a way to make this project alive againor are there still contributors keep working for the development?

**Comment by hishamco** [comment]
@thiennn are you active on this project or you can transfer it and I will take care about the development?

**Comment by thiennn** [comment]
I am back

**Comment by hishamco** [comment]
Could you add me on the team in case you are OOF

**Comment by thiennn** [comment]
@hishamco you are now a maintainer

**Comment by mrccarvalho** [comment]
Good news! 
I used this project architecture to make some web aplications. Not only for e-commerce.
