### ISSUE TITLE
Modifying Product Price with floating values

### ISSUE THREAD

**Issue by MaherJendoubi** [simplcommerce/SimplCommerce#145]
![image](https://cloud.githubusercontent.com/assets/1798510/24477972/680ed438-14d9-11e7-8c4f-59fe421f8275.png)

**Comment by thiennn** [comment]
Handling multiple cultures is hard. The model binding is culture awareness, that mean it will be changed when you change the language of the site.
I'm thinking about using <input type="text" /> instead of <input type="number" />, but another problem is that the json return by controllers is always have "." for decimal separator no matter what the culture of the request is and I don't know how to change that behavior.

**Comment by MaherJendoubi** [comment]
@thiennn What do you think about this : https://github.com/djhaley/InputScrubbingModelBinder
