### ISSUE TITLE
unable publish the site on IIS

### ISSUE THREAD

**Issue by sj185091** [simplcommerce/SimplCommerce#184]
site is working when i run it through visual studio
but i am getting below error every time when i publish it to IIS
An error occurred while starting the application.

_.NET Core X64 v4.1.1.0 | Microsoft.AspNetCore.Hosting version 1.1.0-rtm-22752 | Microsoft Windows 6.1.7601 S |_

**Comment by thiennn** [comment]
![publish](https://cloud.githubusercontent.com/assets/289607/25555816/4ea2c406-2d1a-11e7-9452-954bb3126c5a.png)
1. Change the build configuration to "Release"
2. Update the gulp task to copy .dll in the Release folder instead of Debug
3. Build the solution.
4. Publish
5. Verify the *.dll of modules are being copied to the published folder. For example "Modules\SimplCommerce.Module.ActivityLog\bin"

**Comment by sj185091** [comment]
thanks @thiennn for your assistance
your solution resolved the issue :+1:
