### ISSUE TITLE
Send email when an order is created

### ISSUE THREAD

**Issue by thiennn** [simplcommerce/SimplCommerce#226]
Use SimplCommerce.Infrastructure.Web.RazorViewRenderer for the rendering the body of the email

IEmailSender auto resolved using SimplCommerce.Module.EmailSenderSmtp.EmailSender, we can configure using gmail to send 

SmtpServer: smtp.gmail.com
SmtpPort: 587
SmtpUsername: your email address
SmtpPassword: your password

**Comment by einsteinreloaded** [comment]
is this still on?

**Comment by thiennn** [comment]
yes

**Comment by imaximov** [comment]
Hi, I'm working on it.

**Comment by PeterJD** [comment]
Always consider looking at NopCommerce to identify  how they approach the email issue (what provider they use)

But payment of an order would signify an order, having encountered issues with users placing an order
but failed to make a payment through Paypal, this intern would reduce stock levels, with no payment.
So when should a stock level be decremented and email sent, when notification received of payment from provider (Paypal) 
Whats the point of having an order without payment. Other than a Point of contact?
So if the user realises the mistake and returns to your website to order again but cannot due to being out of stock! so an order and payment of product, should indicate an order?

NopCommerce is quite good system but is too bloated.  Refreshing to see your code

**Comment by thiennn** [comment]
Depend on the payment provider implementation. Currently when do payment via Paypal or Stripe. The order will be created after user have navigated to Paypal or Stripe, but right before the payment being charged. The email should be send and the stock reduce when the order is created. If the charge fail, the user should be informed, he or she can re-do the payment again for cancel the other. If they do nothing, then the order should be cancel by the system after 5 minutes (configurable)
