### ISSUE TITLE
Add multi-tenant support

### ISSUE THREAD

**Issue by tdavisjr** [simplcommerce/SimplCommerce#423]
It would be nice if the store can support multiple storefronts/tenants. Data would have to be separated so one tenant can't see the other tenants data.

Please consider including in v2.

**Comment by thiennn** [comment]
Multiple tenants support seem over complicated for most people.

**Comment by afernandes** [comment]
SimplCommerce is multi-seller?

**Comment by thiennn** [comment]
Mulit-tenant for SimplCommerce should be done at the infrastructure layer. I mean docker container.
Each tenant is a container. 

We will not include this feature to the common version. Because it is complex and required a lot of technical knowledge to setup and maintain which is not suitable for regular users
