### ISSUE TITLE
Migrations

### ISSUE THREAD

**Issue by boros-csongor** [simplcommerce/SimplCommerce#490]
Why did you delete the migrations? :(

**Comment by thiennn** [comment]
Because we want to clean it up :)

You can apply new changes in your existing database by getting the latest MigrationId in '__EFMigrationsHistory' table, then check the commit history, get back the SimplDbContextModelSnapshot.cs at the state of that MigrationId. Then you can do 'Add-Migration' from there. Entity Framework will detect changes since that snapshot

**Comment by boros-csongor** [comment]
Thank you for your response! :)
