### ISSUE TITLE
AngularJS components and Typescript

### ISSUE THREAD

**Issue by vascofernandes** [simplcommerce/SimplCommerce#526]
Hi,

Thanks for the great project.

I have looked at the source as well as previous issues around Angular and typescript.
I understand that moving to Angular 2+ is not trivial. I am not going to suggest that at this point.

What I would like to suggest is to consider start using Typescript and writing AngularJS code using the component API.

I once wrote and article about doing just this: [https://medium.com/@vascofernandes/the-road-to-angular-2-refactoring-angularjs-1-x-applications-for-smoother-upgrade-69c91364bc4c](https://medium.com/@vascofernandes/the-road-to-angular-2-refactoring-angularjs-1-x-applications-for-smoother-upgrade-69c91364bc4c)

Also consider using Custom Elements/Web Components whenever possible, as this would help with making the code-base more framework independent, relying on the platform whenever possible.

Regards

**Comment by justindongqiang** [comment]
@vascofernandes 
Great point and thank you very much for bringing this up. Since we don't have the time and resources, that would be great if you could provide a prototype or some online articles so we could look into it. 

@thiennn perhaps you could create a task for this and add tag "Help Wanted" so that me and @vascofernandes could work on this.

Thanks,
Justin

**Comment by lulzzz** [comment]
I can take a look and see what I come up with that fits into what is being done today.

**Comment by vascofernandes** [comment]
I can take a look and see what I come up with that fits into what is being done today.

**Comment by thiennn** [comment]
@justindongqiang you can also create tasks, and you can pick any items not just the ones with "Help Wanted" label.

**Comment by justindongqiang** [comment]
@vascofernandes sounds great! I look forward to seeing your PoC.

Thanks,
Justin

**Comment by lulzzz** [comment]
The PoC I have at the moment is based on webpack, but I am sure I can implement it with Gulp, if that is preferred, since I used to use Gulp to do this myself.

Before I bring that PoC forwards, i think it is useful to understand some of the things that are not ideal in the current setup, as well define a set of base rules for high quality TS + AngularJS 1.x code; setting a direction for starting to use Web Components when possible and later bring in Angular 2+.

Before we talk about AngularJS 1.x code, I would like to point out a couple of things that are far from ideal. 

https://github.com/simplcommerce/SimplCommerce/blob/master/src/Modules/SimplCommerce.Module.Core/Views/HomeAdmin/Index.cshtml#L13
Should bootstrap AngularJS 1.x manually, i.e., from code.
https://docs.angularjs.org/guide/bootstrap#manual-initialization
Same way as Angular 2+. 


https://github.com/simplcommerce/SimplCommerce/blob/master/src/Modules/SimplCommerce.Module.Core/Views/HomeAdmin/Index.cshtml#L31-L241
Manually loading files like this is an absolute no-go. Please setup bundling. 


 I will make a summary here, as I have written about it before here https://medium.com/@vascofernandes/the-road-to-angular-2-refactoring-angularjs-1-x-applications-for-smoother-upgrade-69c91364bc4c

Interestingly, that article actually needs a correction. In that article I recommend to "use the new component router". Please do not use the AngularJS 1.x Component Router. It was deprecated.
The AngularJS 1.x default router is actually enough to write a high quality app.

- no ng-app, bootstrap manually.
- no ng-controller and do not use angular.controller() - Not existent in Angular 2+
- use only angular.component(), angular.directive(), and angular.service() - these are still present in Angular 2+. Will also make integrating with Web Components easier.
- always use isolated scope - As it the default in Angular 2+ and gives easy integration with Web Components 
- pass data from parent to child, send events up - As recommended in Angular 2+
- remove $scope and $rootScope whenever possible - These do not exist in Angular 2+
- use the new component lifecycle hooks - will match well with Angular 2+


 Just to get a feeling for what the code could look like, here is some of my TS + AngularJS 1.x:


```typescript

@Service(NgModules.Core, Injectables.AnotherTest)
export class AnotherTestService {
    static $inject = [
        Injectables.$log
    ];

    constructor(private $log: ng.ILogService) {
    }

    doStuff() {
        this.$log.log('doing other stuff!');
        return this.doInternal();
    }

    private doInternal() {
        return 'Hello Other World!';
    }
}


@Component({
    module: NgModules.Test,
    selector: 'another-component',
    template: `
        <div>
            {{vm.imageUri}}
        </div>
    `,
    bindings: {
        imageUri: '<',
    }
})
export class AnotherComponent {
    imageUri: string;

    static $inject = [Injectables.AnotherTest];

    constructor(private anotherTest: AnotherTestService) {
    }
}

```

**Comment by vascofernandes** [comment]
The PoC I have at the moment is based on webpack, but I am sure I can implement it with Gulp, if that is preferred, since I used to use Gulp to do this myself.

Before I bring that PoC forwards, i think it is useful to understand some of the things that are not ideal in the current setup, as well define a set of base rules for high quality TS + AngularJS 1.x code; setting a direction for starting to use Web Components when possible and later bring in Angular 2+.

Before we talk about AngularJS 1.x code, I would like to point out a couple of things that are far from ideal. 

https://github.com/simplcommerce/SimplCommerce/blob/master/src/Modules/SimplCommerce.Module.Core/Views/HomeAdmin/Index.cshtml#L13
Should bootstrap AngularJS 1.x manually, i.e., from code.
https://docs.angularjs.org/guide/bootstrap#manual-initialization
Same way as Angular 2+. 


https://github.com/simplcommerce/SimplCommerce/blob/master/src/Modules/SimplCommerce.Module.Core/Views/HomeAdmin/Index.cshtml#L31-L241
Manually loading files like this is an absolute no-go. Please setup bundling. 


 I will make a summary here, as I have written about it before here https://medium.com/@vascofernandes/the-road-to-angular-2-refactoring-angularjs-1-x-applications-for-smoother-upgrade-69c91364bc4c

Interestingly, that article actually needs a correction. In that article I recommend to "use the new component router". Please do not use the AngularJS 1.x Component Router. It was deprecated.
The AngularJS 1.x default router is actually enough to write a high quality app.

- no ng-app, bootstrap manually.
- no ng-controller and do not use angular.controller() - Not existent in Angular 2+
- use only angular.component(), angular.directive(), and angular.service() - these are still present in Angular 2+. Will also make integrating with Web Components easier.
- always use isolated scope - As it the default in Angular 2+ and gives easy integration with Web Components 
- pass data from parent to child, send events up - As recommended in Angular 2+
- remove $scope and $rootScope whenever possible - These do not exist in Angular 2+
- use the new component lifecycle hooks - will match well with Angular 2+


 Just to get a feeling for what the code could look like, here is some of my TS + AngularJS 1.x:


```typescript

@Service(NgModules.Core, Injectables.AnotherTest)
export class AnotherTestService {
    static $inject = [
        Injectables.$log
    ];

    constructor(private $log: ng.ILogService) {
    }

    doStuff() {
        this.$log.log('doing other stuff!');
        return this.doInternal();
    }

    private doInternal() {
        return 'Hello Other World!';
    }
}


@Component({
    module: NgModules.Test,
    selector: 'another-component',
    template: `
        <div>
            {{vm.imageUri}}
        </div>
    `,
    bindings: {
        imageUri: '<',
    }
})
export class AnotherComponent {
    imageUri: string;

    static $inject = [Injectables.AnotherTest];

    constructor(private anotherTest: AnotherTestService) {
    }
}

```

**Comment by thiennn** [comment]
Thank @vascofernandes  for the great effort. But I think the current implement with AngularJS is fine for the next 2 - 3 years. After that we might re-implement the whole back-office
