### ISSUE TITLE
Recommended/tested version of PostgreSQL?

### ISSUE THREAD

**Issue by JanSichula** [simplcommerce/SimplCommerce#66]
Hello,

may I kindly ask what version of PostgreSQL is being used at http://demo.simplcommerce.com/? I am running into issues related to error 42601 when trying to create database on my Windows 10 dev box where I have Win 32 edition of PostgreSQL 9.5 installed.

P. S. We plan to implement a Christian bookstore using your wonderful project.

**Comment by thiennn** [comment]
Hi,
Actually the demo run on Azure SQL Database, but it should work fine on PostgresSQL 9.5. However you need to delete and re-add migration as the instruction https://github.com/simplcommerce/SimplCommerce/blob/master/README.md, another thing is the create sample data function hasn't worked on PostgreSQL yet, because we don't have enough effort to keep the sample script in sync with the SQL Server.

**Comment by thiennn** [comment]
Yes, there are the syntax errors in StaticData_Postgres.sql and I have fixed it

**Comment by JanSichula** [comment]
Thanks for the prompt response. I will give it a second try with fixed StaticData_Postgres.sql as we need to get it running as soon as possible. Now may I kindly suggest that you invest to have PostgreSQL version to be fully working and in sync with MS SQL version for those of us who want to avoid vendor lock-in into expensive MS SQL. The fact is that once some project goes alive with a particular database engine, it becomes almost impossible or too costly to migrate later. That is why we have firmly decided to stick with PostgreSQL from the start. 

P. S. I will later submit a PR for readme.md as some instructions need revision for PostgreSQL.

**Comment by thiennn** [comment]
tested. Work fine on PostgreSQL 9.5
