### ISSUE TITLE
support my sql

### ISSUE THREAD

**Issue by thiennn** [simplcommerce/SimplCommerce#71]
init data script for mysql and sample data script for my sql

**Comment by zbseattle** [comment]
In case it's helpful, here's the mysql variation of StaticData.sql, which I verified worked via the mysql command line. Note that it modifies the columns of tables that use utf-8 strings. Without these mods, the insert statements for such content failed. This might be a function of the state of the .net core migration code, combined with the Pomelo db provider code.
[StaticData_MySql.sql.txt](https://github.com/simplcommerce/SimplCommerce/files/709743/StaticData_MySql.sql.txt)

**Comment by thiennn** [comment]
@zbseattle thank you for the script. Could you please create a pull request?

**Comment by zbseattle** [comment]
Well, maybe. But I think such a pull might be more appropriate in the context of a branch committed to adding MySql support, and additional changes appear to be required for that. And I'm not ready to sign up for that much work currently (especially since I want to next explore whether the existing Postgres support is sufficient). Instead, I thought I'd at least share with you what I did so far.

Please advise further whether you still want this partial work as a pull request. Thanx.

**Comment by thiennn** [comment]
a pull request for just the StaticData_MySql.sql is fine. Thank you

**Comment by zbseattle** [comment]
Ok, I _think_ I did this correctly - I'm not yet a GitHub expert...

I forked simplcommerce/SimplCommerce:master, to zbseattle/SimplCommerce:master, and pushed a change to introduce the file. Then I created a pull request, which appears to have been successful, as #106.

Please let me know if there's anything else I need to do. Thanx!
