### ISSUE TITLE
 Why can't I edit a view while I'm debugging?

### ISSUE THREAD

**Issue by carlosperez1986** [simplcommerce/SimplCommerce#862]
How can i fix this? to modify the view I have to recompile the whole solution again. Work with vs on mac and it's a bit chaotic

i'm using this: https://docs.microsoft.com/es-es/aspnet/core/mvc/views/view-compilation?view=aspnetcore-3.1, but no work.
 
thanks!

**Comment by thiennn** [comment]
Because the views only copied to the WebHost on build. A possible work around is modify directly views in the WebHost (copy views in modules to the Themes in WebHost as the instruction below)

If you want to change the html structure of some particular views. Then following the origin views' structure, create your own views in your theme folder. It will override the original one. Not overrided views will fallback to the origin views. Please check out the SampleTheme.
