### ISSUE TITLE
Improvements and extensions of localizations

### ISSUE THREAD

**Issue by fhebel** [simplcommerce/SimplCommerce#890]
Ciao ragazzi,

for my own purposes I have improved and extended in particular the localization in SimplCommerce. A lot of it was simply diligence work, some of it involved changes to interfaces, controllers, etc.

At this point in time I want to express my appreciation and gratitude to the community, thank the people who supported me (@thienn, @hishamco) and to give something back.

- Are the stakeholders interested in my localization efforts?
- Can everybody agree that the standard texts in the application can be considered en-US (e.g. @Localizer[“Cancel”]), which means that all other languages can be considered a translation?
- In my particular case I needed the shop to be in German (Global.DefaultCultureUI=de-DE), but I wanted to administer the products and everything else in English (Global.DefaultCultureAdminUI=en-GB, providing German translations), in order to offer additional languages (in the future) with fallback to English instead of German. Any interest in that?
- I have already added UI functionality for editing ContactArea translations in the AdminUI. As soon as I have time I’ll add more as needed. Any interest in that?

I’m looking forward to hearing your opinions …

Thanks again in advance.

Tanti saluti

Florian

**Comment by hishamco** [comment]
@ fhebel I need to refresh my mind little bit and check the latest changes in localization, AFAIK there's a default UI culture `Global.DefaultCultureUI` for the site, but I'm not sure for that Admin, because this is tricky little bit, because ASP.NET Core is using one cookie for localization per site

If your plan to support localization in the admin, please let me know we can discuss and see the suitable solution

**Comment by fhebel** [comment]
@hishamco Thanks for your comment. The functionality is already implemented and works. It's not about the language, in which the admin actually sees the UI, it's the language, in which e.g. ProductName, ShortDescription, Descriptions, etc. are saved to the database (e.g. Catalog_Product).

Maybe you have a better idea for the name of the configuration item `Global.DefaultCultureAdminUI`?

**Comment by hishamco** [comment]
> The functionality is already implemented and works

May be, that's why I told you I need to refresh my mind ;) but I don't know how it manage by single cookie?!! unless it uses a database anyhow .. is there wrong with the naming `Global.DefaultCultureAdminUI` this is just a defualt culture, but I expect you could change it then

Regarding your last paragraph I think it is about content localization which is already supported, unfortunately I didn't get what's the point that you stuck on it, so I can understand you better

**Comment by thiennn** [comment]
Hi @fhebel I am very interested on your work. If you have already done, please fire a pull request so that we can take a look. I might easier to understand when look at the code.

**Comment by fhebel** [comment]
https://github.com/fhebel/SimplCommerce/commit/8d6b6d53f2be8449110994fe003946c19fc1e9a5
